name: Delete Non-Compliant Branches

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

permissions:
  contents: write  # Grant the GitHub Actions bot write permissions to delete branches

jobs:
  delete-non-compliant-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Fetch the master branch
        run: git fetch origin master

      - name: Check if branch is identical to master
        id: check
        run: |
          current_branch=$(git rev-parse HEAD)
          master_branch=$(git rev-parse origin/master)
          
          if [ "$current_branch" != "$master_branch" ]; then
            echo "Branch is not identical to master. Deleting branch."
            echo "::set-output name=delete::true"
          else
            echo "::set-output name=delete::false"
          fi

      - name: Delete branch
        if: steps.check.outputs.delete == 'true'
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          echo "Deleting branch $branch_name..."
          git push origin --delete $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
